//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright The Kubernetes Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IbConfig) DeepCopyInto(out *IbConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Pkey != nil {
		in, out := &in.Pkey, &out.Pkey
		*out = new(uint16)
		**out = **in
	}
	if in.TrafficClass != nil {
		in, out := &in.TrafficClass, &out.TrafficClass
		*out = new(uint8)
		**out = **in
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(IbMTU)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IbConfig.
func (in *IbConfig) DeepCopy() *IbConfig {
	if in == nil {
		return nil
	}
	out := new(IbConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IbConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IbMTU) DeepCopyInto(out *IbMTU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IbMTU.
func (in *IbMTU) DeepCopy() *IbMTU {
	if in == nil {
		return nil
	}
	out := new(IbMTU)
	in.DeepCopyInto(out)
	return out
}
