# One pod, one container
# Asking for 2 distinct IB VFs on the same NUMA node for GPUDirect RDMA affinity

---
apiVersion: v1
kind: Namespace
metadata:
  name: ib-test4

---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: ib-test4
  name: dual-ib-vf-same-numa
spec:
  spec:
    devices:
      requests:
      - name: ib-1
        exactly:
          deviceClassName: ib.sigs.k8s.io
          selectors:
          - cel:
              expression: "device.attributes['type'].stringValue == 'VF'"
          - cel:
              expression: "device.attributes['numaNode'].intValue == 0"
      - name: ib-2
        exactly:
          deviceClassName: ib.sigs.k8s.io
          selectors:
          - cel:
              expression: "device.attributes['type'].stringValue == 'VF'"
          - cel:
              expression: "device.attributes['numaNode'].intValue == 0"

---
apiVersion: v1
kind: Pod
metadata:
  namespace: ib-test4
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: ib-devices
  resourceClaims:
  - name: ib-devices
    resourceClaimTemplateName: dual-ib-vf-same-numa
